POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2M2JkNmNmY2MzZDkyNjQyY2Q3MzcxNzciLCJpYXQiOjE2NzM1MjgzMTV9.MM5sgqT1j4NYmRwQbyo3iejBqn861mO249ipnMYVcdU

{
"content": "Token authentication is important to restrict user permissions",
"important": true
}

###

POST https://notes-backend.cyclic.app/api/notes
content-type: application/json

{
"content": "Creating note from VS Code",
"important": true
}
