POST http://localhost:3001/api/notes
content-type: application/json

{
"content": "Note made with new directory structure",
"important": false
}

###

POST https://notes-backend.cyclic.app/api/notes
content-type: application/json

{
"content": "Creating note from VS Code",
"important": true
}
