PUT http://localhost:3001/api/notes/63b5579e44d8db169944786d
content-type: application/json

{
"content": "Creating note from REST plugin with new directory structure. Updated with PUT method"
}

###

PUT https://notes-backend.cyclic.app/api/notes/63b17d6c0be1b747a24ccf32
content-type: application/json

{
"content": "Creating note from the frontend. Updated with PUT method"
}
